"""deleted salt_hashed_password, token_mobile from User

Revision ID: 209cef95ab5c
Revises: 9fb924c39e4b
Create Date: 2024-12-26 19:35:50.477719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209cef95ab5c'
down_revision: Union[str, None] = '9fb924c39e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'routes', ['route_id'])
    op.drop_column('users', 'token_mobile')
    op.drop_column('users', 'salt_hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salt_hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('token_mobile', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'routes', type_='unique')
    # ### end Alembic commands ###
