"""model User: Added last_updated_time, updated authorized_time with default

Revision ID: 66f467264ee5
Revises: 209cef95ab5c
Create Date: 2024-12-27 16:04:09.590844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66f467264ee5'
down_revision: Union[str, None] = '209cef95ab5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_updated_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_updated_time')
    # ### end Alembic commands ###
