"""Coordinate_model_update

Revision ID: 6cc700042058
Revises: 61496e055195
Create Date: 2025-01-26 22:26:35.110123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc700042058'
down_revision: Union[str, None] = '61496e055195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coordinates', sa.Column('order', sa.Integer(), nullable=True))
    op.drop_column('coordinates', 'cord_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coordinates', sa.Column('cord_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('coordinates', 'order')
    # ### end Alembic commands ###
