"""On_deletes

Revision ID: 0f6ccd376f54
Revises: 6cc700042058
Create Date: 2025-01-26 23:04:57.012779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6ccd376f54'
down_revision: Union[str, None] = '6cc700042058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('coordinates_route_id_fkey', 'coordinates', type_='foreignkey')
    op.drop_constraint('coordinates_user_id_fkey', 'coordinates', type_='foreignkey')
    op.create_foreign_key(None, 'coordinates', 'routes', ['route_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'coordinates', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ratings_route_id_fkey', 'ratings', type_='foreignkey')
    op.drop_constraint('ratings_user_id_fkey', 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'routes', ['route_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ratings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('routes_user_id_fkey', 'routes', type_='foreignkey')
    op.create_foreign_key(None, 'routes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.create_foreign_key('routes_user_id_fkey', 'routes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key('ratings_user_id_fkey', 'ratings', 'users', ['user_id'], ['id'])
    op.create_foreign_key('ratings_route_id_fkey', 'ratings', 'routes', ['route_id'], ['id'])
    op.drop_constraint(None, 'coordinates', type_='foreignkey')
    op.drop_constraint(None, 'coordinates', type_='foreignkey')
    op.create_foreign_key('coordinates_user_id_fkey', 'coordinates', 'users', ['user_id'], ['id'])
    op.create_foreign_key('coordinates_route_id_fkey', 'coordinates', 'routes', ['route_id'], ['id'])
    # ### end Alembic commands ###
