"""Update all models, big update 'User'

Revision ID: 3bf09f3fb388
Revises: 0f6ccd376f54
Create Date: 2025-03-14 21:51:34.405119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bf09f3fb388'
down_revision: Union[str, None] = '0f6ccd376f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coordinates', sa.Column('location', sa.String(), nullable=True))
    op.alter_column('coordinates', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('ratings', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('ratings', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('ratings', 'id')
    op.drop_column('ratings', 'created_time')
    op.add_column('routes', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('routes', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_column('routes', 'created_time')
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_active_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('refresh_token_update_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'users', ['telephone_number'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'last_updated_time')
    op.drop_column('users', 'authorized_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authorized_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_updated_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'refresh_token_update_time')
    op.drop_column('users', 'status')
    op.drop_column('users', 'last_active_time')
    op.drop_column('users', 'is_active')
    op.add_column('routes', sa.Column('created_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('routes', 'updated_at')
    op.drop_column('routes', 'created_at')
    op.add_column('ratings', sa.Column('created_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('ratings', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('ratings', 'updated_at')
    op.drop_column('ratings', 'created_at')
    op.alter_column('coordinates', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('coordinates', 'location')
    # ### end Alembic commands ###
