"""empty message

Revision ID: 40651d23d1cf
Revises: 84a17e3b08fc
Create Date: 2026-01-12 02:59:15.922538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40651d23d1cf'
down_revision: Union[str, None] = '84a17e3b08fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False, comment="Уникальный машинный код статуса (например, 'user', 'admin')"),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Человекочитаемое название статуса'),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Права доступа в формате JSONB. Меняется через админку без деплоя'),
    sa.Column('description', sa.Text(), nullable=True, comment='Подробное описание статуса и его возможностей'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Автоматически присваивается новым пользователям'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Приоритет для сортировки (0-100). Чем выше, тем больше прав'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_statuses_code'), 'user_statuses', ['code'], unique=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               comment='Имя пользователя',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment='Уникальный email пользователя',
               existing_nullable=False)
    op.alter_column('users', 'telephone_number',
               existing_type=sa.VARCHAR(),
               comment='Уникальный номер телефона в международном формате',
               existing_nullable=True)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(),
               comment='Фамилия пользователя',
               existing_nullable=True)
    op.alter_column('users', 'location',
               existing_type=sa.VARCHAR(),
               comment='Город или страна проживания',
               existing_nullable=True)
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(),
               comment="Пол: 'M' - мужской, 'F' - женский",
               existing_nullable=True)
    op.alter_column('users', 'birth',
               existing_type=sa.DATE(),
               comment='Дата рождения пользователя',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment='Хэшированный пароль',
               existing_nullable=False)
    op.alter_column('users', 'last_active_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='Время последней активности.',
               existing_nullable=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_last_active_time'), 'users', ['last_active_time'], unique=False)

    op.drop_column('users', 'patronymic')
    op.drop_column('users', 'status')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###

    #
    op.add_column('users',
                  sa.Column('email_verified', sa.Boolean(), nullable=True, comment='Подтвержден ли email пользователя'))
    op.execute("UPDATE users SET email_verified = false WHERE email_verified IS NULL")
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    op.add_column('users', sa.Column('status_id', sa.Integer(), nullable=True, comment='Ссылка на статус пользователя. По умолчанию: обычный пользователь'))
    op.execute("""
        INSERT INTO user_statuses 
            (code, name, is_default, priority, permissions) 
        VALUES
            ('user', 'Обычный пользователь', true, 0, '{"can_edit_own_content": true, "max_routes_per_day": 10}')
        """
    )
    op.execute("""
        UPDATE users 
        SET status_id = (
            SELECT id 
            FROM user_statuses
            WHERE code = 'user'
        )
        WHERE status_id is NULL
        """
    )
    op.alter_column(
        table_name="users", column_name="status_id", existing_type=sa.INTEGER(), nullable=False,
    )
    op.create_foreign_key(None, 'users', 'user_statuses', ['status_id'], ['id'], ondelete='RESTRICT')



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('patronymic', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_last_active_time'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'last_active_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Время последней активности. Обновляется через Redis',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Хэшированный пароль (bcrypt/scrypt)',
               existing_nullable=False)
    op.alter_column('users', 'birth',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Дата рождения пользователя',
               existing_nullable=True)
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Пол: 'M' - мужской, 'F' - женский",
               existing_nullable=True)
    op.alter_column('users', 'location',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Город или страна проживания',
               existing_nullable=True)
    op.alter_column('users', 'surname',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Фамилия пользователя',
               existing_nullable=True)
    op.alter_column('users', 'telephone_number',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Уникальный номер телефона в международном формате',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Уникальный email пользователя',
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Имя пользователя',
               existing_nullable=False)
    op.drop_column('users', 'status_id')
    op.drop_column('users', 'email_verified')
    op.drop_index(op.f('ix_user_statuses_code'), table_name='user_statuses')
    op.drop_table('user_statuses')
    # ### end Alembic commands ###
